# Generated by Django 4.2.11 on 2024-07-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_students_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='birthday',
        ),
    ]
